### ISSUE TITLE
Redundancy in the API for registering implementations of dispatch methods

### ISSUE THREAD

**Issue by taschini** [morepath/reg#50]
Currently, the API to register the implementations of dispatch methods includes:

* ``DispatchMethod.register``
* ``DispatchMethod.register_function``
* ``DispatchMethod.register_auto``
* ``methodify``
* ``methodify_auto``

Inspection of these reveals that
* ``methodify_auto`` is conceptually equivalent to ``methodify`` with a second argument;
* ``DispatchMethod.register_function`` is conceptually equivalent to ``DispatchMethod.register`` + ``methodify``;
* ``DispatchMethod.register_auto`` is conceptually equivalent to ``DispatchMethod.register`` + ``methodify_auto``, and therefore to ``DispatchMethod.register`` + ``methodify``.

The API can therefore be made tighter just by providing:

* ``DispatchMethod.register``
* ``methodify``

Note that ``DispatchMethod.register_function`` is not used anywhere under the Morepath umbrella, ``DispatchMethod.register_auto`` is used in a few places in Morepath, and  ``methodify_auto`` is used a couple of times in Morepath and once in More.static.

**Comment by taschini** [comment]
I noticed that when looking at #47.

**Comment by faassen** [comment]
Okay, so you're proposing:

* ``methodify`` changes its behavior to ``methodify_auto``. We'd lose the ability to methodify unconditionally but Morepath doesn't use it.

* We use ``methodify`` directly in Morepath in the places we used ``register_auto``. That's okay, we already use ``methodify_auto`` anyway.

There's one issue which has to do with the validation logic. ``register_auto`` is uses either ``register``, or ``register_function``. ``register_function`` needs to validate the original unwrapped value (using ``reg.unmethodify``), or alternatively the methodified function gets a full correct signature instead of ``*args, **kw``.

**Comment by faassen** [comment]
I've reworked the APi so there's a ``reg.methodify`` and a ``reg.ummethodify``. I used ``format_signature`` to help create a wrapper, as that allowed the reuse of the validation code.

**Comment by taschini** [comment]
> methodify changes its behavior to methodify_auto. We'd lose the ability to methodify unconditionally but Morepath doesn't use it.

No. You can still have the capability of methodify unconditionally, see 965ac305de32fede57d0f8ca0af4fe24c3aa6f5b.
