### ISSUE TITLE
Switch formatting to black

### ISSUE THREAD

**Issue by faassen** [morepath/reg#57]
I'd like to switch to the Black source code formatting tool to format code. This requires:

* a modification of the developer notes to mention this.

* make Black a development dependency.

* adjustment of any flake8 configuration so it's compatible with Black.

* executing black on all source code.

I like to use Black's integration in vscode and I noticed on large files sometimes Black is rather slow. I suspect we don't have this issue with Reg, though.

I'd also like to configure it to use 80 characters as a line length by default, as I still do prefer this myself.

**Comment by href** [comment]
Personally I'm not a big fan of Black, but I like using `gofmt` and I see its utility. So `+1` from me.

**Comment by RonnyPfannschmidt** [comment]
personally i love to use it in combination with pre-commit to ensure no commit is not formatted as intended

wrt 80 vs 88 - i recall the 88 was specifically chosen to reduce line-noise in various cases, when i tested the difference myself i inded up following the setting black choose,

i highly recommend doing that experiment in order to get a hand on "feel" for the difference
